input.onButtonPressed(Button.A, function on_button_pressed_a() {
    music.playTone(Note.E, music.beat(BeatFraction.Whole))
    music.playTone(Note.E, music.beat(BeatFraction.Whole))
    music.playTone(Note.E, music.beat(BeatFraction.Whole))
    music.playTone(Note.E, music.beat(BeatFraction.Whole))
    music.playTone(Note.E, music.beat(BeatFraction.Whole))
    music.playTone(Note.E, music.beat(BeatFraction.Whole))
    music.playTone(Note.E, music.beat(BeatFraction.Whole))
    music.playTone(Note.G, music.beat(BeatFraction.Whole))
    music.playTone(Note.C, music.beat(BeatFraction.Whole))
    music.playTone(Note.D, music.beat(BeatFraction.Whole))
    music.rest(music.beat(10))
    music.playTone(Note.E, music.beat(BeatFraction.Whole))
    music.playTone(Note.F, music.beat(BeatFraction.Whole))
    music.playTone(Note.F, music.beat(BeatFraction.Whole))
    music.playTone(Note.F, music.beat(BeatFraction.Whole))
    music.playTone(Note.F, music.beat(BeatFraction.Whole))
    music.playTone(Note.F, music.beat(BeatFraction.Whole))
    music.playTone(Note.E, music.beat(BeatFraction.Whole))
    music.playTone(Note.E, music.beat(BeatFraction.Whole))
    music.playTone(Note.E, music.beat(BeatFraction.Whole))
    music.playTone(Note.E, music.beat(BeatFraction.Whole))
    music.rest(music.beat(10))
    music.playTone(Note.E, music.beat(BeatFraction.Whole))
    music.playTone(Note.D, music.beat(BeatFraction.Whole))
    music.playTone(Note.D, music.beat(BeatFraction.Whole))
    music.playTone(Note.E, music.beat(BeatFraction.Whole))
    music.playTone(Note.D, music.beat(BeatFraction.Whole))
    music.playTone(Note.G, music.beat(BeatFraction.Whole))
    music.playTone(Note.E, music.beat(BeatFraction.Whole))
    music.playTone(Note.E, music.beat(BeatFraction.Whole))
    music.playTone(Note.E, music.beat(BeatFraction.Whole))
    music.playTone(Note.E, music.beat(BeatFraction.Whole))
    music.playTone(Note.E, music.beat(BeatFraction.Whole))
    music.rest(music.beat(10))
    music.playTone(Note.E, music.beat(BeatFraction.Whole))
    music.playTone(Note.G, music.beat(BeatFraction.Whole))
    music.playTone(Note.C, music.beat(BeatFraction.Whole))
    music.playTone(Note.D, music.beat(BeatFraction.Whole))
    music.playTone(Note.E, music.beat(BeatFraction.Whole))
    music.playTone(Note.F, music.beat(BeatFraction.Whole))
    music.playTone(Note.F, music.beat(BeatFraction.Whole))
    music.playTone(Note.F, music.beat(BeatFraction.Whole))
    music.playTone(Note.F, music.beat(BeatFraction.Whole))
    music.rest(music.beat(10))
    music.playTone(Note.F, music.beat(BeatFraction.Whole))
    music.playTone(Note.E, music.beat(BeatFraction.Whole))
    music.playTone(Note.E, music.beat(BeatFraction.Whole))
    music.playTone(Note.E, music.beat(BeatFraction.Whole))
    music.playTone(Note.E, music.beat(BeatFraction.Whole))
    music.playTone(Note.G, music.beat(BeatFraction.Whole))
    music.playTone(Note.G, music.beat(BeatFraction.Whole))
    music.playTone(Note.F, music.beat(BeatFraction.Whole))
    music.playTone(Note.D, music.beat(BeatFraction.Whole))
    music.playTone(Note.C, music.beat(BeatFraction.Whole))
})
