def on_button_pressed_a():
    music.play_tone(Note.E, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.E, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.E, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.E, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.E, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.E, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.E, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.G, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.C, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.D, music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(10))
    music.play_tone(Note.E, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.F, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.F, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.F, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.F, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.F, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.E, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.E, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.E, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.E, music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(10))
    music.play_tone(Note.E, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.D, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.D, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.E, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.D, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.G, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.E, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.E, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.E, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.E, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.E, music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(10))
    music.play_tone(Note.E, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.G, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.C, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.D, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.E, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.F, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.F, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.F, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.F, music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(10))
    music.play_tone(Note.F, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.E, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.E, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.E, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.E, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.G, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.G, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.F, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.D, music.beat(BeatFraction.WHOLE))
    music.play_tone(Note.C, music.beat(BeatFraction.WHOLE))
input.on_button_pressed(Button.A, on_button_pressed_a)
        
    
        


